### PR TITLE
add/fix: YankEndOfLine and YankIntoRegister tasks

### PR DESCRIPTION
**Pull request by mertovun**
## What's Changed

- `YankEndOfLine` and `YankIntoRegister` tasks are competed and added to the task index.
- Readme updated accordingly.

## Why These Changes?

Picked up these partially done features as a way to get more familiar with the project and Neovim API. They seemed like the right place to start as a junior Neovim user, making the plugin more engaging.

## Looking Forward

Happy to make further tweaks based on feedback. Excited to contribute more down the line!

---

Feel free to reach out with any suggestions for improvement. Thanks for checking out these updates!

### CODE REVIEW

**Comment by Weyaaron** [comment]
Looks promising to me, I will check it out properly after work. I appreciate the effort!

**Comment by Weyaaron** [comment]
I decided to merge this as is. Minor improvements could be made, but they are somewhat subjective anyway. I will add a few minor alterations based on this in a separate pr. 

 Since your contribution is the first to any project of mine, I got one last question: Did you face any challenges that surprised you? Anything this repo could improve at? I will share my dev setup to ease testing anyway, but I wanted to hear your thoughts as well.

**Comment by mertovun** [comment]
Thank you for merging the PR and for the open dialogue.

Working with Lua and Neovim API is still relatively fresh territory. So, diving into this project is itself a learning curve and I might not have a meaningful insight into the codebase just yet. Regarding the plugin's improvement, after implementing basic text manipulation tasks with lorem ipsum text structured in prose, I think incorporating code-block based tasks would appeal the  NeoVim learners, and using lsp api to programmatically generate such real-life tasks would be challenging itself in a good way.

Excited to continue working together. Appreciate the support!

**Comment by Weyaaron** [comment]
Awesome :)

I have been tinkering with some tasks for lua code in private, maybe I can share these results on a separate branch. Feel free to open some issues to gather these points/open tasks.

**Pull request merged**
